# Generated by Django 3.2.5 on 2021-07-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=13)),
                ('contact_number', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('employment_status', models.CharField(choices=[('U', 'Unemployed'), ('E', 'Employed'), ('S', 'Self-Employed')], max_length=1)),
                ('ownership_status', models.CharField(choices=[('O', 'Owner'), ('T', 'Tenant')], max_length=1)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=200)),
                ('ward_number', models.CharField(max_length=10)),
                ('water_meter', models.CharField(max_length=200)),
                ('electricity_meter', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_data.person')),
            ],
        ),
    ]
